export const MASTER_SKILLS = [
    "3-statement modeling",
    "3d interaction",
    "3d modeling",
    "3d-interaction",
    "3d-modeling",
    "a b testing",
    "a/b testing",
    "a/b-testing",
    "ableton live",
    "acad",
    "academic / university administration",
    "academic administration",
    "academic administration administrator",
    "academic administration advisor",
    "academic administration analyst",
    "academic administration analytics",
    "academic administration compliance",
    "academic administration coordinator",
    "academic administration manager",
    "academic administration operations",
    "academic administration optimization",
    "academic administration reporting",
    "academic administration researcher",
    "academic administration specialist",
    "academic administration strategy",
    "academic quality",
    "academic scheduling",
    "academic support",
    "academic-admin",
    "academic-scheduling",
    "academic-support",
    "access governance",
    "access management",
    "account management",
    "account mgmt",
    "account retention",
    "account-management",
    "accountability",
    "accounting firms / big 4",
    "accounting-firms",
    "accreditation",
    "achieved",
    "acrobat",
    "active listening",
    "actuarial analysis",
    "actuarial-analysis",
    "adaptability",
    "adaptable",
    "admin",
    "admin-office",
    "administered",
    "administration",
    "administrative / office",
    "administrator",
    "admissions support",
    "admissions-support",
    "adobe creative suite",
    "adobe illustrator",
    "adobe indesign",
    "adverse event reporting",
    "adverse-event-reporting",
    "advisor",
    "advisory services",
    "advocacy campaigns",
    "advocacy strategy",
    "advocacy-campaigns",
    "advocacy-strategy",
    "aerospace",
    "aerospace analyst",
    "aerospace analytics",
    "aerospace compliance",
    "aerospace consultant",
    "aerospace coordinator",
    "aerospace manager",
    "aerospace operations",
    "aerospace optimization",
    "aerospace planner",
    "aerospace reporting",
    "aerospace specialist",
    "aerospace strategy",
    "aerospace supervisor",
    "affinity",
    "after effects",
    "agile",
    "agri",
    "agriculture",
    "agriculture / farming / food production",
    "agriculture analyst",
    "agriculture analytics",
    "agriculture compliance",
    "agriculture consultant",
    "agriculture coordinator",
    "agriculture manager",
    "agriculture operations",
    "agriculture optimization",
    "agriculture planner",
    "agriculture reporting",
    "agriculture specialist",
    "agriculture strategy",
    "agriculture supervisor",
    "agronomy",
    "ahrefs",
    "ai",
    "ai / machine learning",
    "ai systems",
    "ai-ml",
    "aiml",
    "airflow",
    "airworthiness",
    "alteryx",
    "amadeus",
    "aml",
    "amplitude",
    "analysis",
    "analysis_and_reporting",
    "analyst",
    "analytical thinking",
    "analytically rigorous",
    "analyzed",
    "anesthesia monitoring",
    "anesthesia-monitoring",
    "animal care",
    "animal welfare",
    "animal-care",
    "animal-welfare",
    "anti money laundering",
    "api",
    "api integration",
    "apis",
    "application development",
    "application programming interface",
    "appointment management",
    "appointment mgmt",
    "appointment scheduling",
    "appointment-management",
    "appointment-scheduling",
    "approvals",
    "approx_unique_terms",
    "ar",
    "ar-vr",
    "arcgis",
    "arch",
    "architect",
    "architected",
    "architectural design",
    "architectural-design",
    "architecture",
    "architecture / interior design",
    "architecture analyst",
    "architecture compliance",
    "architecture consultant",
    "architecture coordinator",
    "architecture director",
    "architecture manager",
    "architecture operations",
    "architecture optimization",
    "architecture reporting",
    "architecture review",
    "architecture specialist",
    "architecture strategist",
    "architecture strategy",
    "architecture-design",
    "argus",
    "arrangement",
    "art direction",
    "art-direction",
    "artificial intelligence",
    "arvr",
    "asana",
    "assay dev",
    "assay development",
    "assay-development",
    "assessment",
    "assessment design",
    "asset accountability",
    "asset allocation",
    "asset integrity",
    "asset maintenance",
    "asset management",
    "asset mgmt",
    "asset pipelines",
    "asset production",
    "asset utilization",
    "asset-accountability",
    "asset-allocation",
    "asset-integrity",
    "asset-maintenance",
    "asset-management",
    "asset-pipelines",
    "asset-production",
    "asset-utilization",
    "associate",
    "assortment planning",
    "assurance services",
    "assurance-services",
    "ats management",
    "ats mgmt",
    "ats-management",
    "ats_keyword_dataset_10k_plus",
    "attention to detail",
    "attribution",
    "audience segmentation",
    "audience targeting",
    "audience-segmentation",
    "audio capture",
    "audio post production",
    "audio post-production",
    "audio production",
    "audio production analyst",
    "audio production compliance",
    "audio production consultant",
    "audio production coordinator",
    "audio production director",
    "audio production manager",
    "audio production operations",
    "audio production optimization",
    "audio production reporting",
    "audio production specialist",
    "audio production strategist",
    "audio production strategy",
    "audio-capture",
    "audio-post-production",
    "audio-production",
    "audit planning",
    "audit readiness",
    "audit support",
    "audit-planning",
    "audit-support",
    "audition",
    "augmented reality",
    "augmented reality / virtual reality",
    "author relations",
    "author-relations",
    "auto",
    "autocad",
    "automated",
    "automation",
    "automation systems",
    "automation-systems",
    "automotive / transportation",
    "automotive-transport",
    "availability",
    "avia",
    "aviation / aerospace",
    "aviation-aerospace",
    "avid media composer",
    "avimark",
    "avionics",
    "avionics systems",
    "avionics-systems",
    "aws",
    "azure",
    "backend services",
    "backend-services",
    "backlog management",
    "backlog mgmt",
    "backlog-management",
    "backup recovery",
    "backup-recovery",
    "banner",
    "batch processing",
    "beau",
    "beauty / wellness / spa",
    "beauty-wellness",
    "behavioral health",
    "behavioral-health",
    "benchmarking",
    "best practices",
    "best-in-class",
    "bi",
    "bid preparation",
    "big4",
    "bigquery",
    "bim coordination",
    "bim-coordination",
    "biostatistics",
    "biotech",
    "biotech advisor",
    "biotech analyst",
    "biotech analytics",
    "biotech compliance",
    "biotech consultant",
    "biotech coordinator",
    "biotech manager",
    "biotech operations",
    "biotech optimization",
    "biotech reporting",
    "biotech specialist",
    "biotech strategy",
    "biotech technician",
    "bitbucket",
    "blackboard",
    "blasting coordination",
    "blasting-coordination",
    "blender",
    "block explorers",
    "block-explorers",
    "blockchain",
    "blockchain analyst",
    "blockchain architect",
    "blockchain consultant",
    "blockchain developer",
    "blockchain engineer",
    "blockchain manager",
    "blockchain operations",
    "blockchain optimization",
    "blockchain reporting",
    "blockchain specialist",
    "blockchain strategy",
    "bloomberg",
    "booking management",
    "booking mgmt",
    "booking optimization",
    "booking-management",
    "booking-optimization",
    "booking.com extranet",
    "brand consistency",
    "brand identity",
    "brand messaging",
    "brand positioning",
    "brand recommendations",
    "brand standards",
    "brand strategy",
    "brand-identity",
    "brand-messaging",
    "brand-positioning",
    "brand-standards",
    "bridge security",
    "bridge-security",
    "briefing materials",
    "briefing notes",
    "briefing-notes",
    "broker coordination",
    "broker relations",
    "broker-coordination",
    "broker-relations",
    "bss oss",
    "bss/oss",
    "budget control",
    "budget forecasting",
    "budget management",
    "budget oversight",
    "budget ownership",
    "budget stewardship",
    "budget tracking",
    "budget-control",
    "budget-oversight",
    "budget-stewardship",
    "budget-tracking",
    "budgeting",
    "build automation",
    "building codes",
    "building-codes",
    "built",
    "bullhorn",
    "burp suite",
    "business",
    "business acumen",
    "business analysis",
    "business dev",
    "business development",
    "business development analyst",
    "business development compliance",
    "business development consultant",
    "business development coordinator",
    "business development director",
    "business development manager",
    "business development operations",
    "business development optimization",
    "business development reporting",
    "business development specialist",
    "business development strategist",
    "business development strategy",
    "business intelligence",
    "business operations",
    "business operations administrator",
    "business operations analyst",
    "business operations analytics",
    "business operations compliance",
    "business operations consultant",
    "business operations coordinator",
    "business operations manager",
    "business operations operations",
    "business operations operations manager",
    "business operations optimization",
    "business operations reporting",
    "business operations specialist",
    "business operations strategy",
    "business ops",
    "business partnering",
    "business reporting",
    "business strategy",
    "business systems",
    "business-analysis",
    "business-savvy",
    "business-strategy",
    "buy side advisory",
    "buy-side advisory",
    "buy-side-advisory",
    "c++",
    "calendar management",
    "calendar mgmt",
    "calendar-management",
    "call quality",
    "call-quality",
    "camera operations",
    "camera ops",
    "camera-operations",
    "campaign analysis",
    "campaign analytics",
    "campaign management",
    "campaign-analytics",
    "candidate sourcing",
    "candidate-sourcing",
    "canva",
    "canvas",
    "cap tables",
    "cap-tables",
    "capacity planning",
    "capacity-planning",
    "capiq",
    "capital raising",
    "capital-raising",
    "carbon accounting",
    "carbon-accounting",
    "card issuing",
    "card-issuing",
    "care coordination",
    "care management platforms",
    "care mgmt platforms",
    "care pathways",
    "care planning",
    "care-coordination",
    "care-management-platforms",
    "care-pathways",
    "carta",
    "case handling",
    "case management",
    "case management system",
    "case mgmt",
    "case notes",
    "case-management",
    "case-notes",
    "caseware",
    "cash flow",
    "cash-flow",
    "catalog management",
    "catalog mgmt",
    "catalog-management",
    "category",
    "catia",
    "cerner",
    "chairside support",
    "chairside-support",
    "championed",
    "change agent",
    "change management",
    "change mgmt",
    "change orders",
    "change-management",
    "change-orders",
    "change-ready",
    "channel optimization",
    "channel planning",
    "checkout system",
    "ci/cd",
    "circular economy",
    "circular-economy",
    "cisco",
    "cision",
    "claims adjudication",
    "claims processing",
    "claims-adjudication",
    "claims-processing",
    "class scheduling",
    "class-scheduling",
    "classroom management",
    "classroom mgmt",
    "classroom-management",
    "client accounting",
    "client advisory",
    "client coaching",
    "client communication",
    "client consultations",
    "client education",
    "client engagement",
    "client management",
    "client presentations",
    "client relationship management",
    "client requirements",
    "client retention",
    "client service",
    "client success",
    "client support",
    "client-accounting",
    "client-advisory",
    "client-coaching",
    "client-communication",
    "client-consultations",
    "client-education",
    "client-facing",
    "client-presentations",
    "client-requirements",
    "client-retention",
    "climate risk",
    "climate tech / sustainability / esg",
    "climate-risk",
    "climate-sustainability",
    "clinical charting",
    "clinical documentation",
    "clinical examinations",
    "clinical reporting",
    "clinical supervision",
    "clinical trials",
    "clinical workflows",
    "clinical-charting",
    "clinical-documentation",
    "clinical-examinations",
    "clinical-supervision",
    "clinical-trials",
    "clinical-workflows",
    "close process",
    "close-process",
    "cloud",
    "cloud analyst",
    "cloud architect",
    "cloud architecture",
    "cloud computing / saas",
    "cloud consultant",
    "cloud developer",
    "cloud engineer",
    "cloud manager",
    "cloud migration",
    "cloud operations",
    "cloud optimization",
    "cloud reporting",
    "cloud software",
    "cloud specialist",
    "cloud strategy",
    "cloud-architecture",
    "cloud-migration",
    "cloud-saas",
    "cloudformation",
    "cmc",
    "cms",
    "coaching",
    "coalition building",
    "coalition-building",
    "code review",
    "collaborated",
    "collaboration",
    "collaborative",
    "command communications",
    "command-communications",
    "commercial awareness",
    "commercially focused",
    "commercially minded",
    "commissioning",
    "committed",
    "committee coordination",
    "committee-coordination",
    "communication",
    "communications",
    "communications analyst",
    "communications analytics",
    "communications compliance",
    "communications consultant",
    "communications coordinator",
    "communications director",
    "communications manager",
    "communications operations",
    "communications optimization",
    "communications reporting",
    "communications specialist",
    "communications strategist",
    "communications strategy",
    "communications-strategy",
    "community engagement",
    "community outreach",
    "community services",
    "community support",
    "community-engagement",
    "community-outreach",
    "community-services",
    "comparable companies",
    "comparable-companies",
    "compensation",
    "competitive analysis",
    "compliance",
    "compliance assessment",
    "compliance controls",
    "compliance mindset",
    "compliance monitoring",
    "compliance tech",
    "compliance technology",
    "compliance tracking",
    "compliance-aware",
    "compliance-controls",
    "compliance-technology",
    "compliance-tracking",
    "component traceability",
    "component-traceability",
    "computer vision",
    "computer-vision",
    "conceived",
    "confidentiality",
    "configuration",
    "configured",
    "conflict resolution",
    "confluence",
    "cons",
    "consensus building",
    "consolidated",
    "const",
    "construction",
    "construction / civil engineering",
    "construction analyst",
    "construction analytics",
    "construction compliance",
    "construction consultant",
    "construction coordinator",
    "construction documentation",
    "construction estimator",
    "construction manager",
    "construction operations",
    "construction optimization",
    "construction oversight",
    "construction reporting",
    "construction safety",
    "construction specialist",
    "construction strategy",
    "construction supervisor",
    "construction-documentation",
    "construction-engineering",
    "construction-oversight",
    "construction-safety",
    "consultant",
    "consultative",
    "consultative approach",
    "consulting / strategy",
    "consulting-strategy",
    "container orchestration",
    "container-orchestration",
    "content acquisition",
    "content authoring",
    "content calendars",
    "content development",
    "content execution",
    "content marketing",
    "content strategy",
    "content-acquisition",
    "content-authoring",
    "content-calendars",
    "content-marketing",
    "continuous deployment",
    "continuous improvement",
    "continuous integration",
    "continuous-improvement",
    "contract administration",
    "contract lifecycle management",
    "contract lifecycle mgmt",
    "contract oversight",
    "contract review",
    "contract-lifecycle-management",
    "contract-review",
    "control systems",
    "control-systems",
    "controls",
    "controls oversight",
    "conversion optimization",
    "conversion tracking",
    "conversion-optimization",
    "coordinated",
    "coordination",
    "coordinator",
    "copyediting",
    "copywriting",
    "core_keywords",
    "cornerstone",
    "corporate governance",
    "corporate-governance",
    "cost accounting",
    "cost analysis",
    "cost control",
    "cost estimation",
    "cost optimization",
    "cost reduction",
    "cost-accounting",
    "cost-estimation",
    "cost-optimization",
    "counseling",
    "course platform",
    "coverage analysis",
    "coverage-analysis",
    "created",
    "creative briefs",
    "creative design",
    "creative design analyst",
    "creative design compliance",
    "creative design consultant",
    "creative design coordinator",
    "creative design director",
    "creative design manager",
    "creative design operations",
    "creative design optimization",
    "creative design reporting",
    "creative design specialist",
    "creative design strategist",
    "creative design strategy",
    "creative direction",
    "creative production",
    "creative thinking",
    "creative-briefs",
    "creative-direction",
    "creative_and_media",
    "crew coordination",
    "crisis intervention",
    "crisis-intervention",
    "critical thinking",
    "crm",
    "crm hygiene",
    "crm platform",
    "crm-hygiene",
    "crop management",
    "crop mgmt",
    "crop-management",
    "cross functional collaboration",
    "cross-functional",
    "cross-functional alignment",
    "cross-functional collaboration",
    "cross-functional leadership",
    "cross-functional-collaboration",
    "cross-industry",
    "cross-industry (universal)",
    "crowdstrike",
    "cultural awareness",
    "curiosity",
    "curriculum dev",
    "curriculum development",
    "curriculum mapping",
    "curriculum planning",
    "curriculum-development",
    "curriculum-mapping",
    "customer acquisition",
    "customer due diligence",
    "customer experience",
    "customer experience design",
    "customer feedback",
    "customer focus",
    "customer notifications",
    "customer relationship management",
    "customer retention",
    "customer satisfaction",
    "customer service",
    "customer service advisor",
    "customer service analyst",
    "customer service analytics",
    "customer service business partner",
    "customer service compliance",
    "customer service consultant",
    "customer service coordinator",
    "customer service manager",
    "customer service operations",
    "customer service optimization",
    "customer service reporting",
    "customer service specialist",
    "customer service strategy",
    "customer success",
    "customer support",
    "customer-centric",
    "customer-feedback",
    "customer-notifications",
    "customer-obsessed",
    "customer-retention",
    "customer-satisfaction",
    "customer-service",
    "customer-support",
    "customer_and_client",
    "cvent",
    "cyber",
    "cybersecurity",
    "cybersecurity analyst",
    "cybersecurity architect",
    "cybersecurity consultant",
    "cybersecurity developer",
    "cybersecurity engineer",
    "cybersecurity manager",
    "cybersecurity operations",
    "cybersecurity optimization",
    "cybersecurity reporting",
    "cybersecurity specialist",
    "cybersecurity strategy",
    "dao governance",
    "dao-governance",
    "dashboarding",
    "data",
    "data & analytics",
    "data administrator",
    "data analysis",
    "data analyst",
    "data analytics",
    "data architect",
    "data collection",
    "data consultant",
    "data developer",
    "data engineer",
    "data entry",
    "data governance",
    "data manager",
    "data modeling",
    "data operations",
    "data optimization",
    "data pipelines",
    "data reporting",
    "data specialist",
    "data storytelling",
    "data strategy",
    "data visualization",
    "data-analysis",
    "data-analytics",
    "data-collection",
    "data-driven",
    "data-driven decision making",
    "data-entry",
    "data-modeling",
    "data-storytelling",
    "data-visualization",
    "data_and_ai",
    "datadog",
    "dataset_name",
    "davinci resolve",
    "daw workflows",
    "daw-workflows",
    "dbt",
    "dcf analysis",
    "dcf-analysis",
    "deadline management",
    "deadline-oriented",
    "deal analysis",
    "deal execution",
    "deal negotiation",
    "deal sourcing",
    "deal structuring",
    "deal-analysis",
    "deal-negotiation",
    "deal-sourcing",
    "deal-structuring",
    "debugged",
    "debugging",
    "decision making",
    "decision-maker",
    "deep learning",
    "deep-learning",
    "defense",
    "defense advisor",
    "defense analyst",
    "defense analytics",
    "defense compliance",
    "defense consultant",
    "defense coordinator",
    "defense manager",
    "defense officer",
    "defense operations",
    "defense optimization",
    "defense reporting",
    "defense specialist",
    "defense strategy",
    "defi protocols",
    "defi-protocols",
    "defined",
    "delivered",
    "delivery assurance",
    "delivery management",
    "delivery performance",
    "delivery slas",
    "delivery-assurance",
    "delivery-focused",
    "delivery-performance",
    "delivery-slas",
    "demand planning",
    "demand-planning",
    "dent",
    "dental",
    "dental / optometry",
    "dental advisor",
    "dental analyst",
    "dental analytics",
    "dental compliance",
    "dental consultant",
    "dental coordinator",
    "dental manager",
    "dental operations",
    "dental optimization",
    "dental reporting",
    "dental specialist",
    "dental strategy",
    "dental technician",
    "dental-optometry",
    "dentrix",
    "deployed",
    "deployment",
    "deployment pipeline",
    "design / creative",
    "design coordination",
    "design dev",
    "design development",
    "design patterns",
    "design review",
    "design systems",
    "design-coordination",
    "design-creative",
    "design-development",
    "design-systems",
    "designed",
    "designed for resume-to-job-description matching and ats keyword extraction.",
    "destination knowledge",
    "destination-knowledge",
    "deswik",
    "detail orientation",
    "detail-oriented",
    "dev budgets",
    "developed",
    "developer",
    "development budgets",
    "development-budgets",
    "diagnostic testing",
    "diagnostic-testing",
    "differentiated instruction",
    "differentiated-instruction",
    "digital campaigns",
    "digital health",
    "digital health advisor",
    "digital health analyst",
    "digital health analytics",
    "digital health compliance",
    "digital health consultant",
    "digital health coordinator",
    "digital health manager",
    "digital health operations",
    "digital health optimization",
    "digital health reporting",
    "digital health specialist",
    "digital health strategy",
    "digital health technician",
    "digital marketing",
    "digital mktg",
    "digital payments",
    "digital transformation",
    "digital-campaigns",
    "digital-health",
    "digital-marketing",
    "digital-payments",
    "digital_and_tools",
    "directed",
    "director",
    "discharge planning",
    "discharge-planning",
    "discovery workshops",
    "discretion",
    "dispatch coordination",
    "dispatch management",
    "dispatch mgmt",
    "dispatch planning",
    "dispatch systems",
    "dispatch-management",
    "dispatch-planning",
    "dispatch-systems",
    "distributed systems",
    "distributed-systems",
    "distribution deliverables",
    "distribution-deliverables",
    "docker",
    "document automation",
    "document control",
    "document drafting",
    "document preparation",
    "document-automation",
    "document-control",
    "document-drafting",
    "documentation",
    "documentation accuracy",
    "documentation control",
    "documentation management",
    "documentation review",
    "docusign",
    "domain",
    "donor relations",
    "donor-relations",
    "dot compliance",
    "dot-compliance",
    "downstream operations",
    "downstream ops",
    "downstream-operations",
    "drawings review",
    "drawings-review",
    "drilling operations",
    "drilling ops",
    "drilling-operations",
    "driven",
    "driver apps",
    "driver safety",
    "driver-apps",
    "driver-safety",
    "drove",
    "drug safety",
    "drug-safety",
    "dsgn",
    "duck creek",
    "due diligence",
    "due-diligence",
    "dune",
    "e discovery",
    "e-discovery",
    "ecommerce",
    "ecommerce advisor",
    "ecommerce analyst",
    "ecommerce analytics",
    "ecommerce compliance",
    "ecommerce coordinator",
    "ecommerce manager",
    "ecommerce operations",
    "ecommerce optimization",
    "ecommerce planner",
    "ecommerce reporting",
    "ecommerce specialist",
    "ecommerce strategy",
    "ecommerce supervisor",
    "editing workflows",
    "editing-workflows",
    "editorial planning",
    "editorial-planning",
    "edtech",
    "edu",
    "education",
    "education & research",
    "education / teaching",
    "education administrator",
    "education advisor",
    "education analyst",
    "education analytics",
    "education compliance",
    "education coordinator",
    "education manager",
    "education operations",
    "education optimization",
    "education reporting",
    "education researcher",
    "education specialist",
    "education strategy",
    "education tech",
    "education technology",
    "education technology administrator",
    "education technology advisor",
    "education technology analyst",
    "education technology analytics",
    "education technology compliance",
    "education technology coordinator",
    "education technology manager",
    "education technology operations",
    "education technology optimization",
    "education technology reporting",
    "education technology researcher",
    "education technology specialist",
    "education technology strategy",
    "education-teaching",
    "education-technology",
    "efficiency-minded",
    "ehr",
    "electronic medical record",
    "email marketing",
    "email-marketing",
    "embedded finance",
    "embedded-finance",
    "emerging & niche",
    "emerging technology",
    "emerging_tech",
    "emissions tracking",
    "emissions-tracking",
    "emoney",
    "emotional intelligence",
    "empathy",
    "employee relations",
    "employee-relations",
    "employer branding",
    "employer-branding",
    "emr",
    "enabled",
    "endpoint security",
    "endpoint-security",
    "energy",
    "energy / oil & gas",
    "energy analyst",
    "energy analytics",
    "energy compliance",
    "energy consultant",
    "energy coordinator",
    "energy efficiency",
    "energy manager",
    "energy operations",
    "energy optimization",
    "energy planner",
    "energy reporting",
    "energy specialist",
    "energy strategy",
    "energy supervisor",
    "energy trading",
    "energy-efficiency",
    "energy-oil-gas",
    "energy-trading",
    "engagement",
    "engagement surveys",
    "engagement-surveys",
    "engineer",
    "engineered",
    "engineering change control",
    "engineering-change-control",
    "enhanced",
    "enrg",
    "enterprise resource planning",
    "enterprising",
    "environmental compliance",
    "environmental social and governance",
    "environmental-compliance",
    "epic",
    "equipment maintenance",
    "equipment operation",
    "equipment reliability",
    "equipment-maintenance",
    "equipment-reliability",
    "erp",
    "erp systems",
    "escalation handling",
    "escalation-handling",
    "esg",
    "esg reporting",
    "esg-reporting",
    "established",
    "estate planning",
    "estate-planning",
    "estimator",
    "eta prediction",
    "eta-prediction",
    "ethers.js",
    "ethics compliance",
    "ethics-compliance",
    "etl",
    "evaluated",
    "evaluation",
    "event",
    "event management",
    "event management advisor",
    "event management analyst",
    "event management analytics",
    "event management business partner",
    "event management compliance",
    "event management consultant",
    "event management coordinator",
    "event management manager",
    "event management operations",
    "event management optimization",
    "event management reporting",
    "event management specialist",
    "event management strategy",
    "event mgmt",
    "event planning",
    "event support",
    "event-management",
    "event-planning",
    "eventbrite",
    "evidence synthesis",
    "evidence-based",
    "evidence-based practice",
    "excel",
    "executed",
    "execution",
    "execution-focused",
    "executive presentations",
    "executive reporting",
    "executive support",
    "executive-presentations",
    "executive-support",
    "exercise assessment",
    "exercise-assessment",
    "exit planning",
    "exit-planning",
    "expanded",
    "expense reports",
    "expense-reports",
    "experiment design",
    "experiment tracking",
    "experiment-design",
    "experiment-tracking",
    "experimental design",
    "experimental-design",
    "experimentation",
    "extract transform load",
    "fabric selection",
    "fabric-selection",
    "facilitated",
    "facilitation",
    "facility operations",
    "facility ops",
    "facility-operations",
    "fact checking",
    "fact-checking",
    "factset",
    "faculty support",
    "faculty-support",
    "farm operations",
    "farm ops",
    "farm-operations",
    "fash",
    "fashion",
    "fashion / apparel",
    "fashion analyst",
    "fashion compliance",
    "fashion consultant",
    "fashion coordinator",
    "fashion director",
    "fashion manager",
    "fashion operations",
    "fashion optimization",
    "fashion reporting",
    "fashion specialist",
    "fashion strategist",
    "fashion strategy",
    "fashion-apparel",
    "fast-paced",
    "feasibility analysis",
    "feasibility studies",
    "feasibility-studies",
    "feature delivery",
    "feature engineering",
    "feature prioritization",
    "feature-engineering",
    "feature-prioritization",
    "fhir",
    "fiber deployment",
    "fiber-deployment",
    "fiduciary standards",
    "fiduciary-standards",
    "field operations",
    "figma",
    "film",
    "film / tv / video production",
    "film-tv",
    "fin",
    "final cut pro",
    "finance",
    "finance / accounting",
    "finance advisor",
    "finance analyst",
    "finance analytics",
    "finance associate",
    "finance compliance",
    "finance consultant",
    "finance manager",
    "finance modeling",
    "finance operations",
    "finance operations manager",
    "finance optimization",
    "finance reporting",
    "finance specialist",
    "finance strategy",
    "finance-accounting",
    "finance_and_business",
    "financial analysis",
    "financial analytics",
    "financial apis",
    "financial crime compliance",
    "financial modeling",
    "financial planning",
    "financial reporting",
    "financial statements",
    "financial-analysis",
    "financial-apis",
    "financial-planning",
    "financial-reporting",
    "financial-statements",
    "fintech",
    "fintech advisor",
    "fintech analyst",
    "fintech associate",
    "fintech compliance",
    "fintech consultant",
    "fintech manager",
    "fintech operations",
    "fintech operations manager",
    "fintech optimization",
    "fintech reporting",
    "fintech specialist",
    "fintech strategy",
    "fit sessions",
    "fit-sessions",
    "fitness",
    "fitness advisor",
    "fitness analyst",
    "fitness analytics",
    "fitness business partner",
    "fitness compliance",
    "fitness consultant",
    "fitness coordinator",
    "fitness manager",
    "fitness operations",
    "fitness optimization",
    "fitness programming",
    "fitness reporting",
    "fitness specialist",
    "fitness strategy",
    "fitness-programming",
    "fleet operations",
    "fleet ops",
    "fleet visibility",
    "fleet-operations",
    "fleet-visibility",
    "flight operations",
    "flight ops",
    "flight software",
    "flight-operations",
    "flight-software",
    "follow-through",
    "follow-up",
    "food safety",
    "food-safety",
    "forecast accuracy",
    "forecast-accuracy",
    "forecasted",
    "forecasting",
    "forward-thinking",
    "foundry",
    "fraud detection",
    "fraud prevention",
    "fraud-detection",
    "fraud-prevention",
    "front office",
    "front-office",
    "frontend architecture",
    "frontend-architecture",
    "ftech",
    "fuel efficiency",
    "fuel-efficiency",
    "fulfillment analytics",
    "fulfillment-analytics",
    "fundraising",
    "future-ready",
    "game",
    "game analyst",
    "game architect",
    "game balancing",
    "game consultant",
    "game design",
    "game developer",
    "game engineer",
    "game manager",
    "game operations",
    "game optimization",
    "game reporting",
    "game specialist",
    "game strategy",
    "game-balancing",
    "game-design",
    "gameplay systems",
    "gameplay-systems",
    "gaming",
    "gaming / game development",
    "garment construction",
    "garment-construction",
    "gcp",
    "gds",
    "general ledger",
    "general-ledger",
    "generated",
    "geology support",
    "geology-support",
    "gesture controls",
    "gesture-controls",
    "ghg protocol tools",
    "gis",
    "git",
    "github",
    "github actions",
    "gitlab",
    "global_tool_count",
    "go to market",
    "go-to expert",
    "go-to-market",
    "go-to-market strategy",
    "goal planning",
    "gong",
    "google ads",
    "google analytics",
    "google classroom",
    "google docs",
    "google workspace",
    "gov",
    "governance",
    "government / public sector",
    "government relations",
    "government-public",
    "government-relations",
    "grading",
    "grant admin",
    "grant administration",
    "grant management",
    "grant support",
    "grant writing",
    "grant-administration",
    "grant-support",
    "grant-writing",
    "graphpad prism",
    "greenhouse",
    "grid operations",
    "grid ops",
    "grid reliability",
    "grid-operations",
    "grid-reliability",
    "ground operations",
    "ground ops",
    "ground-operations",
    "group therapy",
    "group travel",
    "group-therapy",
    "group-travel",
    "growth marketing",
    "growth marketing analyst",
    "growth marketing analytics",
    "growth marketing compliance",
    "growth marketing consultant",
    "growth marketing coordinator",
    "growth marketing director",
    "growth marketing manager",
    "growth marketing operations",
    "growth marketing optimization",
    "growth marketing reporting",
    "growth marketing specialist",
    "growth marketing strategist",
    "growth marketing strategy",
    "growth mktg",
    "growth strategy",
    "growth-focused",
    "growth-minded",
    "guest experience",
    "guest relations",
    "guest-experience",
    "guest-relations",
    "guidance",
    "guidewire",
    "gxp",
    "hands-on",
    "hardhat",
    "harvest scheduling",
    "harvest-scheduling",
    "headhunting",
    "headset experience",
    "health data integration",
    "health-data-integration",
    "healthcare",
    "healthcare & life sciences",
    "healthcare / medical",
    "healthcare advisor",
    "healthcare analyst",
    "healthcare analytics",
    "healthcare compliance",
    "healthcare consultant",
    "healthcare coordinator",
    "healthcare manager",
    "healthcare operations",
    "healthcare optimization",
    "healthcare reporting",
    "healthcare specialist",
    "healthcare strategy",
    "healthcare technician",
    "healthcare-compliance",
    "healthcare-medical",
    "healthcare_and_life_sciences",
    "healthtech",
    "healthtech / digital health",
    "high-impact",
    "high-performing",
    "high-velocity",
    "hipaa",
    "hipaa compliance",
    "hipaa-compliance",
    "hl7",
    "hlth",
    "hootsuite",
    "hosp",
    "hospital operations",
    "hospital ops",
    "hospital-operations",
    "hospitality",
    "hospitality & retail",
    "hospitality / food",
    "hospitality advisor",
    "hospitality analyst",
    "hospitality analytics",
    "hospitality compliance",
    "hospitality coordinator",
    "hospitality manager",
    "hospitality operations",
    "hospitality optimization",
    "hospitality planner",
    "hospitality reporting",
    "hospitality specialist",
    "hospitality strategy",
    "hospitality supervisor",
    "hospitality-food",
    "housekeeping operations",
    "housekeeping ops",
    "housekeeping-operations",
    "hr",
    "hr analytics",
    "hr compliance",
    "hr-analytics",
    "hr-compliance",
    "hse",
    "htech",
    "hubspot",
    "hubspot crm",
    "human resources",
    "human resources advisor",
    "human resources analyst",
    "human resources analytics",
    "human resources business partner",
    "human resources compliance",
    "human resources consultant",
    "human resources coordinator",
    "human resources manager",
    "human resources operations",
    "human resources optimization",
    "human resources reporting",
    "human resources specialist",
    "human resources strategy",
    "human-resources",
    "hyperparameter tuning",
    "hyperparameter-tuning",
    "hypothesis testing",
    "hypothesis-testing",
    "iac",
    "iam",
    "identity access management",
    "identity access mgmt",
    "identity and access management",
    "identity verification",
    "identity-access-management",
    "imanage",
    "immersive simulation",
    "immersive storytelling",
    "immersive tech",
    "immersive technology",
    "immersive technology analyst",
    "immersive technology analytics",
    "immersive technology architect",
    "immersive technology compliance",
    "immersive technology consultant",
    "immersive technology engineer",
    "immersive technology manager",
    "immersive technology operations",
    "immersive technology optimization",
    "immersive technology reporting",
    "immersive technology researcher",
    "immersive technology specialist",
    "immersive technology strategy",
    "immersive-storytelling",
    "impact measurement",
    "impact-measurement",
    "impact-oriented",
    "implementation",
    "implementation planning",
    "implementation-planning",
    "implemented",
    "improved",
    "improvement plans",
    "in game economy",
    "in-game economy",
    "in-game-economy",
    "incident handling",
    "incident reporting",
    "incident response",
    "incident-reporting",
    "incident-response",
    "includes 71 industries based on the provided taxonomy and 500 job roles.",
    "increased",
    "indesign",
    "industrial automation",
    "industrial-automation",
    "industries",
    "industry-leading",
    "industry_id",
    "industry_name",
    "inference optimization",
    "inference-optimization",
    "influenced",
    "influencing",
    "infra as code",
    "infrastructure as code",
    "initiated",
    "initiative",
    "initiative taking",
    "injury prevention",
    "injury-prevention",
    "innovation",
    "innovation strategy",
    "innovative",
    "innovator",
    "ins",
    "insight-led",
    "insightful",
    "insights",
    "inspection",
    "instructional delivery",
    "instructional design",
    "instructional-delivery",
    "instructional-design",
    "insurance",
    "insurance advisor",
    "insurance analyst",
    "insurance analytics",
    "insurance associate",
    "insurance compliance",
    "insurance consultant",
    "insurance manager",
    "insurance operations",
    "insurance operations manager",
    "insurance optimization",
    "insurance reporting",
    "insurance specialist",
    "insurance strategy",
    "insurance verification",
    "insurance-verification",
    "integrated",
    "integration",
    "integration testing",
    "integration-testing",
    "integrity",
    "intelligence analysis",
    "intelligence-analysis",
    "intelligent automation",
    "intercom",
    "interface design",
    "internal communications",
    "internal controls",
    "internal-communications",
    "internal-controls",
    "interoperability",
    "interpersonal skills",
    "interview coordination",
    "interview-coordination",
    "inventory analysis",
    "inventory control",
    "inventory management",
    "inventory mgmt",
    "inventory optimization",
    "inventory planning",
    "inventory-control",
    "inventory-management",
    "inventory-optimization",
    "inventory-planning",
    "investment banking",
    "investment banking advisor",
    "investment banking analyst",
    "investment banking associate",
    "investment banking compliance",
    "investment banking consultant",
    "investment banking manager",
    "investment banking operations",
    "investment banking operations manager",
    "investment banking optimization",
    "investment banking reporting",
    "investment banking specialist",
    "investment banking strategy",
    "investment committee",
    "investment memos",
    "investment policy",
    "investment-banking",
    "investment-committee",
    "investment-memos",
    "investment-policy",
    "ironclad",
    "irrigation planning",
    "irrigation-planning",
    "issue campaigns",
    "issue resolution",
    "issue triage",
    "issue-campaigns",
    "issue-triage",
    "itinerary design",
    "itinerary-design",
    "java",
    "javascript",
    "jenkins",
    "jira",
    "job postings",
    "job-postings",
    "judgment",
    "juniper",
    "kanban",
    "key performance indicators",
    "keywords",
    "klaviyo",
    "know your customer",
    "knowledge base",
    "knowledge management",
    "knowledge mgmt",
    "knowledge-base",
    "knowledge-management",
    "kpi",
    "kpi reporting",
    "kpi tracking",
    "kpi-reporting",
    "kpi-tracking",
    "kpis",
    "kubeflow",
    "kubernetes",
    "kyc",
    "l2 scaling",
    "l2-scaling",
    "labor scheduling",
    "labor-scheduling",
    "laboratory protocols",
    "laboratory research",
    "laboratory samples",
    "laboratory-protocols",
    "laboratory-research",
    "laboratory-samples",
    "labview",
    "land acquisition",
    "land-acquisition",
    "language models",
    "last mile delivery",
    "last-mile delivery",
    "last-mile-delivery",
    "latency optimization",
    "latency-optimization",
    "launched",
    "layout coordination",
    "layout design",
    "layout-coordination",
    "layout-design",
    "lead generation",
    "lead qualification",
    "lead-generation",
    "lead-qualification",
    "leadership",
    "leadership_and_execution",
    "lean implementation",
    "lean manufacturing",
    "lean-manufacturing",
    "learning & development",
    "learning agility",
    "learning analytics",
    "learning and dev",
    "learning and development",
    "learning guidance",
    "learning management system",
    "learning outcomes",
    "learning platform",
    "learning platforms",
    "learning support",
    "learning-analytics",
    "learning-and-development",
    "learning-outcomes",
    "learning-platforms",
    "leasing",
    "leasing strategy",
    "leasing-strategy",
    "led",
    "ledger reconciliation",
    "ledger-reconciliation",
    "legal",
    "legal advisor",
    "legal analyst",
    "legal analytics",
    "legal business partner",
    "legal compliance",
    "legal consultant",
    "legal coordinator",
    "legal manager",
    "legal operations",
    "legal ops",
    "legal optimization",
    "legal reporting",
    "legal research",
    "legal specialist",
    "legal strategy",
    "legal tech",
    "legal technology",
    "legal technology advisor",
    "legal technology analyst",
    "legal technology analytics",
    "legal technology business partner",
    "legal technology compliance",
    "legal technology consultant",
    "legal technology coordinator",
    "legal technology manager",
    "legal technology operations",
    "legal technology optimization",
    "legal technology reporting",
    "legal technology specialist",
    "legal technology strategy",
    "legal workflow automation",
    "legal-analytics",
    "legal-operations",
    "legal-research",
    "legal-workflow-automation",
    "legaltech",
    "legaltech / regtech",
    "legislative research",
    "legislative-research",
    "lesson planning",
    "lesson-planning",
    "level design",
    "level-design",
    "lever",
    "lexisnexis",
    "lgtech",
    "lighting setup",
    "lighting-setup",
    "line planning",
    "line-planning",
    "linkedin recruiter",
    "linkedin sales navigator",
    "literature review",
    "literature-review",
    "litigation support",
    "litigation-support",
    "live ops",
    "live sound",
    "live-ops",
    "live-sound",
    "lms",
    "lms integration",
    "lms-integration",
    "load forecasting",
    "load-forecasting",
    "location management",
    "location mgmt",
    "location-management",
    "logic pro",
    "logistics coordination",
    "logistics planning",
    "logistics support",
    "logistics tech",
    "logistics tech / last-mile delivery",
    "logistics technology",
    "logistics technology analyst",
    "logistics technology analytics",
    "logistics technology compliance",
    "logistics technology consultant",
    "logistics technology coordinator",
    "logistics technology manager",
    "logistics technology operations",
    "logistics technology optimization",
    "logistics technology planner",
    "logistics technology reporting",
    "logistics technology specialist",
    "logistics technology strategy",
    "logistics technology supervisor",
    "logistics-coordination",
    "logistics-planning",
    "logistics-support",
    "logistics-tech",
    "looker",
    "loss ratios",
    "loss-ratios",
    "lp reporting",
    "lp-reporting",
    "m&a execution",
    "m&a-execution",
    "machine learning",
    "machine learning analyst",
    "machine learning architect",
    "machine learning consultant",
    "machine learning developer",
    "machine learning engineer",
    "machine learning manager",
    "machine learning operations",
    "machine learning optimization",
    "machine learning reporting",
    "machine learning specialist",
    "machine learning strategy",
    "machine vision",
    "machine-learning",
    "machine-vision",
    "mailchimp",
    "maintained",
    "maintenance",
    "maintenance planning",
    "maintenance-planning",
    "managed",
    "manager",
    "manufacturing",
    "manufacturing analyst",
    "manufacturing analytics",
    "manufacturing compliance",
    "manufacturing consultant",
    "manufacturing coordinator",
    "manufacturing manager",
    "manufacturing operations",
    "manufacturing optimization",
    "manufacturing planner",
    "manufacturing reporting",
    "manufacturing specialist",
    "manufacturing strategy",
    "manufacturing supervisor",
    "manuscript review",
    "manuscript-review",
    "market analysis",
    "market diligence",
    "market-analysis",
    "market-diligence",
    "marketing / growth",
    "marketing automation",
    "marketing-automation",
    "marketing-growth",
    "marketing_and_sales",
    "marketplace operations",
    "marketplace ops",
    "marketplace-operations",
    "marqeta",
    "mastering",
    "material selection",
    "material-selection",
    "materiality assessments",
    "materiality-assessments",
    "matlab",
    "measured",
    "meddra",
    "media",
    "media / communications",
    "media monitoring",
    "media outreach",
    "media-communications",
    "media-monitoring",
    "media-outreach",
    "medical histories",
    "medical records",
    "medical writing",
    "medical-histories",
    "medical-records",
    "medical-writing",
    "meeting coordination",
    "meeting management",
    "meeting-coordination",
    "meltwater",
    "member retention",
    "member-retention",
    "mental health",
    "mental health / counseling",
    "mental health advisor",
    "mental health advocacy",
    "mental health analyst",
    "mental health analytics",
    "mental health compliance",
    "mental health consultant",
    "mental health coordinator",
    "mental health manager",
    "mental health operations",
    "mental health optimization",
    "mental health reporting",
    "mental health specialist",
    "mental health strategy",
    "mental health technician",
    "mental-health",
    "mental-health-advocacy",
    "mentored",
    "mentoring",
    "menu planning",
    "merchandising",
    "mes",
    "messaging framework",
    "meta ads manager",
    "metamask",
    "metasploit",
    "metrics tracking",
    "metrics-driven",
    "mfg",
    "mhlth",
    "microservices",
    "microsoft office",
    "mil",
    "military / defense",
    "military-defense",
    "mindbody",
    "mine",
    "mine planning",
    "mine-planning",
    "mining",
    "mining / extraction",
    "mining analyst",
    "mining analytics",
    "mining compliance",
    "mining consultant",
    "mining coordinator",
    "mining manager",
    "mining operations",
    "mining optimization",
    "mining planner",
    "mining reporting",
    "mining specialist",
    "mining strategy",
    "mining supervisor",
    "minitab",
    "miro",
    "mission design",
    "mission planning",
    "mission-critical",
    "mission-design",
    "mission-planning",
    "mixed reality",
    "mixing",
    "mixpanel",
    "mkt",
    "ml",
    "ml models",
    "mlflow",
    "mlops",
    "model deployment",
    "model monitoring",
    "model training",
    "model-deployment",
    "model-monitoring",
    "model-training",
    "modeled",
    "modeling",
    "moneyguidepro",
    "monitored",
    "monitoring",
    "month end close",
    "month-end close",
    "month-end-close",
    "moodle",
    "morningstar",
    "motion graphics",
    "motion-graphics",
    "mri",
    "ms project",
    "multi tenant architecture",
    "multi-tenant architecture",
    "multi-tenant-architecture",
    "multidisciplinary collaboration",
    "multiplayer systems",
    "multiplayer-systems",
    "multitasking",
    "music",
    "music / audio production",
    "music editing",
    "music-audio",
    "music-editing",
    "mvp",
    "mysql",
    "natural language processing",
    "needs assessment",
    "negotiated",
    "negotiation",
    "negotiation skills",
    "nessus",
    "netsuite",
    "network operations",
    "network ops",
    "network planning",
    "network security",
    "network-operations",
    "network-planning",
    "network-security",
    "nft marketplaces",
    "nft-marketplaces",
    "nlp",
    "noc monitoring",
    "noc-monitoring",
    "node.js",
    "nokia oss",
    "non-financial reporting",
    "non-profit / social impact",
    "nonprofit-social",
    "notes",
    "notion",
    "npo",
    "nutrition guidance",
    "nutrition-guidance",
    "object oriented programming",
    "object-oriented programming",
    "object-oriented-programming",
    "observability",
    "offer management",
    "offer mgmt",
    "offer-management",
    "office administration",
    "office administration administrator",
    "office administration analyst",
    "office administration analytics",
    "office administration compliance",
    "office administration consultant",
    "office administration coordinator",
    "office administration manager",
    "office administration officer",
    "office administration operations",
    "office administration optimization",
    "office administration reporting",
    "office administration specialist",
    "office administration strategy",
    "office operations",
    "office ops",
    "office-operations",
    "officer",
    "okta",
    "omnichannel operations",
    "omnichannel ops",
    "omnichannel-operations",
    "on chain analytics",
    "on-chain analytics",
    "on-chain-analytics",
    "onboarding",
    "onsite execution",
    "onsite-execution",
    "open banking",
    "open dental",
    "open-banking",
    "opentable",
    "openzeppelin",
    "opera pms",
    "operated",
    "operating model",
    "operating-model",
    "operational excellence",
    "operational readiness",
    "operational-readiness",
    "operationally excellent",
    "operations",
    "operations & logistics",
    "operations / logistics",
    "operations analyst",
    "operations analytics",
    "operations compliance",
    "operations consultant",
    "operations coordinator",
    "operations management",
    "operations manager",
    "operations mgmt",
    "operations operations",
    "operations optimization",
    "operations oversight",
    "operations planner",
    "operations reporting",
    "operations specialist",
    "operations strategy",
    "operations supervisor",
    "operations support",
    "operations-logistics",
    "operations-management",
    "operations_and_industry",
    "operations_and_process",
    "ops",
    "ops management",
    "ops manager",
    "optimization",
    "optimization roadmap",
    "optimized",
    "oracle",
    "orbital analysis",
    "orbital-analysis",
    "orchestrated",
    "order fulfillment",
    "order orchestration",
    "order tracking",
    "order-fulfillment",
    "order-orchestration",
    "ore processing",
    "ore-processing",
    "org effectiveness",
    "organic search",
    "organization",
    "organizational awareness",
    "organized",
    "outage management",
    "outage mgmt",
    "outage-management",
    "outcomes-based",
    "outreach",
    "oversaw",
    "ownership",
    "ownership mentality",
    "ownership mindset",
    "p&l",
    "p&l management",
    "p&l mgmt",
    "p&l ownership",
    "p&l-management",
    "paid search",
    "paid social",
    "paid-social",
    "pandas",
    "parent communication",
    "parent-communication",
    "partner",
    "partnership dev",
    "partnership development",
    "partnership-development",
    "patience",
    "patient assessment",
    "patient care",
    "patient education",
    "patient engagement",
    "patient intake",
    "patient records",
    "patient safety",
    "patient-assessment",
    "patient-care",
    "patient-education",
    "patient-engagement",
    "patient-intake",
    "patient-safety",
    "payload integration",
    "payload-integration",
    "payment gateways",
    "payment-gateways",
    "penetration testing",
    "penetration-testing",
    "people & services",
    "people management",
    "people operations",
    "people team",
    "people-first",
    "peoplesoft",
    "perforce",
    "performance management",
    "performance metrics",
    "performance mgmt",
    "performance optimization",
    "performance orientation",
    "performance profiling",
    "performance tracking",
    "performance-driven",
    "performance-management",
    "performance-optimization",
    "performance-oriented",
    "performance-profiling",
    "performance-tracking",
    "permit coordination",
    "permit drawings",
    "permit to work",
    "permit tracking",
    "permit-coordination",
    "permit-drawings",
    "permit-to-work",
    "pharma",
    "pharma-biotech",
    "pharmaceuticals / biotech",
    "pharmacovigilance",
    "pharmacy inventory",
    "pharmacy-inventory",
    "photon",
    "physics systems",
    "physics-systems",
    "pi system",
    "pipeline automation",
    "pipeline management",
    "pipeline mgmt",
    "pipeline operations",
    "pipeline ops",
    "pipeline-management",
    "pipeline-operations",
    "pitch books",
    "pitch-books",
    "pitchbook",
    "plaid",
    "planned",
    "planner",
    "planning",
    "planning approvals",
    "planning-approvals",
    "platform adoption",
    "platform standards",
    "player progression",
    "player-progression",
    "plc",
    "plc programming",
    "plc-programming",
    "plm",
    "pmo",
    "pmo support",
    "pmo-support",
    "podcast production",
    "podcast-production",
    "point of sale",
    "policy",
    "policy & advocacy",
    "policy adherence",
    "policy admin",
    "policy administration",
    "policy advisor",
    "policy analysis",
    "policy analyst",
    "policy analytics",
    "policy compliance",
    "policy consultant",
    "policy coordinator",
    "policy implementation",
    "policy interpretation",
    "policy manager",
    "policy officer",
    "policy operations",
    "policy optimization",
    "policy renewals",
    "policy reporting",
    "policy specialist",
    "policy strategy",
    "policy-administration",
    "policy-advocacy",
    "policy-analysis",
    "policy-implementation",
    "policy-interpretation",
    "policy-renewals",
    "portfolio management",
    "portfolio mgmt",
    "portfolio monitoring",
    "portfolio oversight",
    "portfolio reporting",
    "portfolio review",
    "portfolio support",
    "portfolio-management",
    "portfolio-monitoring",
    "portfolio-reporting",
    "portfolio-support",
    "pos",
    "positioning",
    "post event reporting",
    "post production",
    "post-event reporting",
    "post-event-reporting",
    "post-production",
    "post-sales support",
    "postgresql",
    "power bi",
    "power systems",
    "power-systems",
    "powerpoint",
    "pre production",
    "pre-production",
    "predictive maintenance",
    "predictive-maintenance",
    "prefix",
    "premiere pro",
    "premium calculations",
    "premium-calculations",
    "presentation formatting",
    "presentation materials",
    "presentation skills",
    "presentation-formatting",
    "press releases",
    "press-releases",
    "preventive care",
    "preventive maintenance",
    "preventive-care",
    "preventive-maintenance",
    "pricing analysis",
    "pricing strategy",
    "pricing-strategy",
    "primavera p6",
    "prioritization",
    "prioritized",
    "privacy controls",
    "privacy-controls",
    "private equity",
    "private equity advisor",
    "private equity analyst",
    "private equity associate",
    "private equity compliance",
    "private equity consultant",
    "private equity manager",
    "private equity operations",
    "private equity operations manager",
    "private equity optimization",
    "private equity reporting",
    "private equity specialist",
    "private equity strategy",
    "pro forma modeling",
    "pro tools",
    "pro-forma-modeling",
    "proactive",
    "problem escalation",
    "problem solving",
    "problem-solver",
    "process analysis",
    "process controls",
    "process engineering",
    "process execution",
    "process improvement",
    "process improvement mindset",
    "process optimization",
    "process redesign",
    "process-engineering",
    "process-focused",
    "process-improvement",
    "procore",
    "procurement",
    "procurement compliance",
    "procurement-compliance",
    "prod",
    "produced",
    "product",
    "product administrator",
    "product adoption",
    "product analyst",
    "product analytics",
    "product architect",
    "product compliance",
    "product consultant",
    "product dev",
    "product developer",
    "product development",
    "product discovery",
    "product engineer",
    "product knowledge",
    "product management",
    "product manager",
    "product operations",
    "product optimization",
    "product reporting",
    "product specialist",
    "product strategy",
    "product-adoption",
    "product-analytics",
    "product-development",
    "product-discovery",
    "product-knowledge",
    "product-management",
    "product-strategy",
    "productboard",
    "production optimization",
    "production planning",
    "production scheduling",
    "production targets",
    "production workflows",
    "production-optimization",
    "production-planning",
    "production-targets",
    "production-workflows",
    "program administration",
    "program coordination",
    "program delivery",
    "program design",
    "program evaluation",
    "program leadership",
    "program management",
    "program mgmt",
    "program office",
    "program operations",
    "program ops",
    "program-delivery",
    "program-management",
    "program-operations",
    "programmed",
    "progress monitoring",
    "project & admin",
    "project controls",
    "project coordination",
    "project delivery",
    "project financing",
    "project governance",
    "project management",
    "project management administrator",
    "project management analyst",
    "project management analytics",
    "project management compliance",
    "project management consultant",
    "project management coordinator",
    "project management manager",
    "project management office",
    "project management officer",
    "project management operations",
    "project management optimization",
    "project management reporting",
    "project management specialist",
    "project management strategy",
    "project mgmt",
    "project planning",
    "project scheduling",
    "project-controls",
    "project-delivery",
    "project-financing",
    "project-management",
    "project-planning",
    "project-scheduling",
    "promotions execution",
    "proofreading",
    "propdev",
    "property dev",
    "property development",
    "property development analyst",
    "property development analytics",
    "property development compliance",
    "property development consultant",
    "property development coordinator",
    "property development estimator",
    "property development manager",
    "property development operations",
    "property development optimization",
    "property development reporting",
    "property development specialist",
    "property development strategy",
    "property development supervisor",
    "property management",
    "property mgmt",
    "property valuations",
    "property-development",
    "property-management",
    "property-valuations",
    "prospecting",
    "protocol adherence",
    "protocol compliance",
    "protocol-compliance",
    "prototyping",
    "provider enablement",
    "provider-enablement",
    "pub",
    "public & social",
    "public accounting",
    "public accounting advisor",
    "public accounting analyst",
    "public accounting analytics",
    "public accounting business partner",
    "public accounting compliance",
    "public accounting consultant",
    "public accounting coordinator",
    "public accounting manager",
    "public accounting operations",
    "public accounting optimization",
    "public accounting reporting",
    "public accounting specialist",
    "public accounting strategy",
    "public admin",
    "public administration",
    "public affairs",
    "public consultation",
    "public policy",
    "public relations",
    "public reporting",
    "public sector",
    "public sector advisor",
    "public sector analyst",
    "public sector analytics",
    "public sector compliance",
    "public sector consultant",
    "public sector coordinator",
    "public sector manager",
    "public sector officer",
    "public sector operations",
    "public sector optimization",
    "public sector reporting",
    "public sector specialist",
    "public sector strategy",
    "public service delivery",
    "public speaking",
    "public-administration",
    "public-affairs",
    "public-consultation",
    "public-relations",
    "public-reporting",
    "publication schedules",
    "publication support",
    "publication writing",
    "publication-schedules",
    "publication-writing",
    "publishing",
    "publishing analyst",
    "publishing compliance",
    "publishing consultant",
    "publishing coordinator",
    "publishing director",
    "publishing manager",
    "publishing operations",
    "publishing optimization",
    "publishing reporting",
    "publishing specialist",
    "publishing strategist",
    "publishing strategy",
    "purchase orders",
    "purchase-orders",
    "python",
    "pytorch",
    "qa",
    "quality assurance",
    "quality care",
    "quality checks",
    "quality control",
    "quality improvement",
    "quality inspections",
    "quality metrics",
    "quality mindset",
    "quality monitoring",
    "quality standards",
    "quality-care",
    "quality-conscious",
    "quality-control",
    "quality-focused",
    "quality-improvement",
    "quality-inspections",
    "quality-standards",
    "qualtrics",
    "quantity takeoff",
    "quickbooks",
    "radio access network",
    "radio-access-network",
    "raid logs",
    "raid-logs",
    "raiser's edge",
    "rapid prototyping",
    "react",
    "real estate",
    "real estate & construction",
    "real estate analyst",
    "real estate analytics",
    "real estate compliance",
    "real estate consultant",
    "real estate coordinator",
    "real estate estimator",
    "real estate manager",
    "real estate operations",
    "real estate optimization",
    "real estate reporting",
    "real estate specialist",
    "real estate strategy",
    "real estate supervisor",
    "real time rendering",
    "real-estate",
    "real-time rendering",
    "real-time-rendering",
    "reaper",
    "recommendations",
    "reconciliations",
    "recording sessions",
    "recording-sessions",
    "records management",
    "records mgmt",
    "records-management",
    "recr",
    "recruitment",
    "recruitment / staffing agencies",
    "recruitment advisor",
    "recruitment analyst",
    "recruitment analytics",
    "recruitment business partner",
    "recruitment compliance",
    "recruitment consultant",
    "recruitment coordinator",
    "recruitment manager",
    "recruitment metrics",
    "recruitment operations",
    "recruitment optimization",
    "recruitment reporting",
    "recruitment specialist",
    "recruitment strategy",
    "recruitment-metrics",
    "recruitment-staffing",
    "redcap",
    "redis",
    "reduced",
    "refined",
    "refinery processes",
    "refinery-processes",
    "registration operations",
    "registration ops",
    "registration-operations",
    "regulatory analysis",
    "regulatory compliance",
    "regulatory monitoring",
    "regulatory readiness",
    "regulatory standards",
    "regulatory submissions",
    "regulatory-analysis",
    "regulatory-compliance",
    "regulatory-monitoring",
    "regulatory-standards",
    "regulatory-submissions",
    "relationship building",
    "relationship management",
    "relationship mgmt",
    "relationship-focused",
    "relationship-management",
    "relativity",
    "release automation",
    "release management",
    "reliability",
    "reliability analysis",
    "reliability-analysis",
    "reliable",
    "remote monitoring",
    "remote-monitoring",
    "rendering optimization",
    "rendering-optimization",
    "renewable energy",
    "renewable energy analyst",
    "renewable energy analytics",
    "renewable energy compliance",
    "renewable energy consultant",
    "renewable energy coordinator",
    "renewable energy manager",
    "renewable energy operations",
    "renewable energy optimization",
    "renewable energy planner",
    "renewable energy reporting",
    "renewable energy specialist",
    "renewable energy strategy",
    "renewable energy supervisor",
    "renewable projects",
    "renewable-energy",
    "renewable-projects",
    "rent rolls",
    "rent-rolls",
    "replenishment",
    "report automation",
    "report writing",
    "report-automation",
    "reported",
    "reporting",
    "reputation management",
    "reputation mgmt",
    "reputation-management",
    "requirements analysis",
    "requirements gathering",
    "requirements management",
    "requirements mgmt",
    "requirements-gathering",
    "requirements-management",
    "res",
    "research",
    "research / science",
    "research administrator",
    "research advisor",
    "research analysis",
    "research analyst",
    "research analytics",
    "research and development",
    "research compliance",
    "research coordinator",
    "research design",
    "research manager",
    "research methods",
    "research operations",
    "research optimization",
    "research reporting",
    "research researcher",
    "research specialist",
    "research strategy",
    "research-design",
    "research-science",
    "researched",
    "researcher",
    "reservation management",
    "reservation mgmt",
    "reservation support",
    "reservation systems",
    "reservation-management",
    "reservation-systems",
    "resilience",
    "resilient",
    "resolved",
    "resource allocation",
    "resource estimation",
    "resource management",
    "resource planning",
    "resource-estimation",
    "resource-planning",
    "resourceful",
    "resourcefulness",
    "rest apis",
    "rest-apis",
    "restaurant operations",
    "restaurant ops",
    "restaurant-operations",
    "results-driven",
    "results-oriented",
    "retail",
    "retail / e-commerce",
    "retail sales",
    "retail system",
    "retail-ecommerce",
    "retail-sales",
    "retention",
    "retirement planning",
    "retirement-planning",
    "returns management",
    "returns mgmt",
    "returns-management",
    "revenue growth",
    "revenue management",
    "revenue mgmt",
    "revenue optimization",
    "revenue-growth",
    "revenue-management",
    "revit",
    "rfis",
    "rhino",
    "rights management",
    "rights mgmt",
    "rights-management",
    "risk analysis",
    "risk assessment",
    "risk awareness",
    "risk logs",
    "risk management",
    "risk mgmt",
    "risk profiling",
    "risk selection",
    "risk-assessment",
    "risk-logs",
    "risk-management",
    "risk-profiling",
    "risk-selection",
    "roadmap planning",
    "roadmapping",
    "roadmaps",
    "robo",
    "robot path planning",
    "robot-path-planning",
    "robotics",
    "robotics / automation",
    "robotics analyst",
    "robotics analytics",
    "robotics architect",
    "robotics compliance",
    "robotics consultant",
    "robotics engineer",
    "robotics integration",
    "robotics manager",
    "robotics operations",
    "robotics optimization",
    "robotics reporting",
    "robotics researcher",
    "robotics specialist",
    "robotics strategy",
    "robotics-automation",
    "robotics-integration",
    "role_family",
    "role_name",
    "roles",
    "root cause analysis",
    "root-cause-analysis",
    "ros",
    "route optimization",
    "route-optimization",
    "routing",
    "run of show",
    "run-of-show",
    "saas",
    "saas delivery",
    "saas implementation",
    "saas-delivery",
    "saas-implementation",
    "sabre",
    "safety compliance",
    "safety interlocks",
    "safety management systems",
    "safety mgmt systems",
    "safety-compliance",
    "safety-interlocks",
    "safety-management-systems",
    "sales",
    "sales / business dev",
    "sales analysis",
    "sales forecasting",
    "sales reporting",
    "sales, marketing & creative",
    "sales-bizdev",
    "sales-forecasting",
    "sales-reporting",
    "salesforce",
    "salesforce nonprofit cloud",
    "salesforce service cloud",
    "sample handling",
    "sanitation standards",
    "sanitation-standards",
    "sap",
    "sap pm",
    "sas",
    "scada",
    "scalability",
    "scalable",
    "scalable solutions",
    "scale-minded",
    "scaled",
    "scenario analysis",
    "scenario planning",
    "scene lighting",
    "scene-lighting",
    "schedule management",
    "schedule tracking",
    "schedule-tracking",
    "scheduled",
    "scheduling",
    "schematic design",
    "schematic-design",
    "scientific communication",
    "scientific-communication",
    "scikit-learn",
    "scope management",
    "scope mgmt",
    "scope review",
    "scope-management",
    "screening",
    "script dev",
    "script development",
    "script-development",
    "scrum",
    "search ads",
    "search engine marketing",
    "search engine optimization",
    "seasonal assortment",
    "seasonal planning",
    "seasonal-assortment",
    "secure communications systems",
    "security audits",
    "security awareness",
    "security protocols",
    "security-audits",
    "security-awareness",
    "security-protocols",
    "self-management",
    "self-starter",
    "sell side process",
    "sell-side process",
    "sell-side-process",
    "sem",
    "semrush",
    "sensor integration",
    "sensor-integration",
    "seo",
    "seo optimization",
    "serverless",
    "service assurance",
    "service delivery",
    "service excellence",
    "service improvement",
    "service integration",
    "service level agreement",
    "service orientation",
    "service planning",
    "service quality",
    "service recovery",
    "service reliability",
    "service standards",
    "service support",
    "service targets",
    "service-assurance",
    "service-delivery",
    "service-excellence",
    "service-improvement",
    "service-oriented",
    "service-quality",
    "service-recovery",
    "service-reliability",
    "service-standards",
    "service_and_people_ops",
    "servicenow",
    "shift management",
    "shift supervision",
    "shift-supervision",
    "shipped",
    "shoot scheduling",
    "shoot-scheduling",
    "shopify",
    "siem",
    "signal flow",
    "signal-flow",
    "simplepractice",
    "simplified",
    "simulation",
    "site analysis",
    "site communication",
    "site coordination",
    "site due diligence",
    "site operations",
    "site ops",
    "site safety",
    "site supervision",
    "site visits",
    "site-analysis",
    "site-due-diligence",
    "site-operations",
    "site-supervision",
    "site-visits",
    "situational awareness",
    "situational-awareness",
    "six sigma",
    "six-sigma",
    "sketch",
    "sketchup",
    "skill_clusters",
    "sla",
    "sla adherence",
    "sla management",
    "sla-adherence",
    "slack",
    "slas",
    "smart contracts",
    "smart-contracts",
    "smartsheet",
    "snowflake",
    "social impact",
    "social impact advisor",
    "social impact analyst",
    "social impact analytics",
    "social impact compliance",
    "social impact consultant",
    "social impact coordinator",
    "social impact manager",
    "social impact officer",
    "social impact operations",
    "social impact optimization",
    "social impact reporting",
    "social impact specialist",
    "social impact strategy",
    "software",
    "software / tech",
    "software administrator",
    "software analyst",
    "software architect",
    "software as a service",
    "software consultant",
    "software dev",
    "software developer",
    "software development",
    "software engineer",
    "software manager",
    "software operations",
    "software optimization",
    "software reporting",
    "software specialist",
    "software strategy",
    "software-development",
    "software-tech",
    "software_development",
    "soil health",
    "soil-health",
    "solar projects",
    "solar-projects",
    "solarwinds",
    "solidity",
    "solidworks",
    "solution assessment",
    "solution design",
    "solution orientation",
    "solutions-oriented",
    "sop adherence",
    "sop-adherence",
    "sops",
    "sound design",
    "sound-design",
    "space",
    "space planning",
    "space systems",
    "space systems analyst",
    "space systems analytics",
    "space systems architect",
    "space systems compliance",
    "space systems consultant",
    "space systems engineer",
    "space systems manager",
    "space systems operations",
    "space systems optimization",
    "space systems reporting",
    "space systems researcher",
    "space systems specialist",
    "space systems strategy",
    "space tech",
    "space-planning",
    "space-systems",
    "space-tech",
    "spark",
    "spatial computing",
    "spatial overlays",
    "spatial-computing",
    "speaker management",
    "speaker mgmt",
    "speaker-management",
    "spearheaded",
    "specialist",
    "splunk",
    "sponsorship fulfillment",
    "sponsorship-fulfillment",
    "sport",
    "sports & fitness / personal training",
    "sports-fitness",
    "spss",
    "sql",
    "sql querying",
    "sql-querying",
    "square",
    "staff supervision",
    "stakeholder advisory",
    "stakeholder alignment",
    "stakeholder communication",
    "stakeholder engagement",
    "stakeholder management",
    "stakeholder mapping",
    "stakeholder mgmt",
    "stakeholder-alignment",
    "stakeholder-communication",
    "stakeholder-engagement",
    "stakeholder-focused",
    "stakeholder-management",
    "stakeholder-mapping",
    "staking",
    "standardized",
    "statistical analysis",
    "statistical-analysis",
    "statistics",
    "status reporting",
    "status-reporting",
    "sterilization protocols",
    "sterilization-protocols",
    "stk",
    "storyboarding",
    "storytelling",
    "strategic",
    "strategic leadership",
    "strategic partner",
    "strategic planning",
    "strategic thinking",
    "strategist",
    "strategy consulting",
    "strategy consulting advisor",
    "strategy consulting analyst",
    "strategy consulting analytics",
    "strategy consulting business partner",
    "strategy consulting compliance",
    "strategy consulting consultant",
    "strategy consulting coordinator",
    "strategy consulting manager",
    "strategy consulting operations",
    "strategy consulting optimization",
    "strategy consulting reporting",
    "strategy consulting specialist",
    "strategy consulting strategy",
    "streamlined",
    "stripe",
    "structured",
    "structured thinker",
    "student advising",
    "student assessment",
    "student engagement",
    "student records",
    "student support",
    "student-assessment",
    "student-engagement",
    "student-records",
    "style guides",
    "style-guides",
    "subcontractor management",
    "subcontractor mgmt",
    "subcontractor-management",
    "subject matter expert",
    "subscriber management",
    "subscriber mgmt",
    "subscriber-management",
    "subscription software",
    "succession planning",
    "succession-planning",
    "supervised",
    "supervisor",
    "supplier management",
    "supplier mgmt",
    "supplier-management",
    "supply chain",
    "supply chain / procurement",
    "supply chain analyst",
    "supply chain analytics",
    "supply chain compliance",
    "supply chain consultant",
    "supply chain coordinator",
    "supply chain manager",
    "supply chain operations",
    "supply chain optimization",
    "supply chain planner",
    "supply chain reporting",
    "supply chain specialist",
    "supply chain strategy",
    "supply chain supervisor",
    "supply continuity",
    "supply planning",
    "supply-chain",
    "supply-continuity",
    "supply-planning",
    "support operations",
    "support ops",
    "support services",
    "support-operations",
    "supported",
    "surgical assistance",
    "surgical-assistance",
    "surpac",
    "sustainability",
    "sustainability analyst",
    "sustainability analytics",
    "sustainability architect",
    "sustainability compliance",
    "sustainability consultant",
    "sustainability disclosures",
    "sustainability engineer",
    "sustainability manager",
    "sustainability operations",
    "sustainability optimization",
    "sustainability practices",
    "sustainability reporting",
    "sustainability researcher",
    "sustainability specialist",
    "sustainability strategy",
    "sustainability-disclosures",
    "sustainability-practices",
    "sustainability-reporting",
    "sustainability-strategy",
    "synonym_entry_count",
    "synthesized",
    "system administration",
    "system configuration",
    "system design",
    "system setup",
    "system-design",
    "systems design",
    "systems engineering",
    "systems integration",
    "systems testing",
    "systems thinking",
    "systems-engineering",
    "systems-testing",
    "tableau",
    "talent acquisition",
    "talent pipelines",
    "talent planning",
    "talent-acquisition",
    "talent-pipelines",
    "task allocation",
    "tax compliance",
    "tax efficient investing",
    "tax-compliance",
    "tax-efficient investing",
    "tax-efficient-investing",
    "team development",
    "team leadership",
    "team player",
    "team supervision",
    "teams",
    "teamwork",
    "tech",
    "technical design",
    "technical documentation",
    "technical records",
    "technical roadmap",
    "technical support",
    "technical-design",
    "technical-records",
    "technician",
    "technology",
    "telco",
    "telecom",
    "telecommunications",
    "telecommunications analyst",
    "telecommunications architect",
    "telecommunications consultant",
    "telecommunications developer",
    "telecommunications engineer",
    "telecommunications infrastructure",
    "telecommunications manager",
    "telecommunications operations",
    "telecommunications optimization",
    "telecommunications reporting",
    "telecommunications specialist",
    "telecommunications strategy",
    "telecommunications-infrastructure",
    "telematics",
    "telemedicine",
    "telemetry",
    "tenant relations",
    "tenant-relations",
    "tensorflow",
    "term sheets",
    "term-sheets",
    "terraform",
    "territory planning",
    "territory-planning",
    "test campaigns",
    "test-campaigns",
    "tested",
    "testing",
    "text analytics",
    "the graph",
    "thought leader",
    "threat detection",
    "threat-detection",
    "ticket resolution",
    "ticket-resolution",
    "time management",
    "tms",
    "token launches",
    "token-launches",
    "tokenomics",
    "tool administration",
    "tool operation",
    "tool_detection",
    "tools",
    "total keyword records exceed 10,000 across roles, tools, soft skills, buzzwords, and core industry terms.",
    "total_keyword_records",
    "trained",
    "trainerize",
    "training",
    "training coordination",
    "training delivery",
    "training-coordination",
    "transaction monitoring",
    "transaction support",
    "transaction-monitoring",
    "transaction-support",
    "transformation",
    "transformational",
    "transformed",
    "transport compliance",
    "transport scheduling",
    "transport-compliance",
    "transport-scheduling",
    "transportation",
    "transportation analyst",
    "transportation analytics",
    "transportation compliance",
    "transportation consultant",
    "transportation coordinator",
    "transportation manager",
    "transportation operations",
    "transportation optimization",
    "transportation planner",
    "transportation reporting",
    "transportation specialist",
    "transportation strategy",
    "transportation supervisor",
    "trauma informed care",
    "trauma-informed care",
    "trauma-informed-care",
    "travel",
    "travel & tourism",
    "travel advisor",
    "travel advisory",
    "travel analyst",
    "travel analytics",
    "travel arrangements",
    "travel compliance",
    "travel coordination",
    "travel coordinator",
    "travel manager",
    "travel operations",
    "travel optimization",
    "travel planner",
    "travel reporting",
    "travel specialist",
    "travel strategy",
    "travel supervisor",
    "travel-arrangements",
    "travel-compliance",
    "travel-tourism",
    "treatment planning",
    "treatment plans",
    "treatment protocols",
    "treatment-planning",
    "treatment-plans",
    "treatment-protocols",
    "trello",
    "trend analysis",
    "trend forecasting",
    "trend-forecasting",
    "trip planning",
    "trip-planning",
    "troubleshot",
    "trusted advisor",
    "trusted partner",
    "trvl",
    "typescript",
    "typography",
    "ui",
    "underwriting",
    "unit testing",
    "unit-testing",
    "unity",
    "universal",
    "unreal engine",
    "upselling",
    "upstream operations",
    "upstream ops",
    "upstream-operations",
    "usability",
    "usage reporting",
    "usage-reporting",
    "user centered design",
    "user experience",
    "user interface",
    "user onboarding",
    "user research",
    "user retention",
    "user stories",
    "user testing",
    "user-centered design",
    "user-centered-design",
    "user-onboarding",
    "user-research",
    "user-retention",
    "user-testing",
    "util",
    "utilities / power / renewables",
    "utilities-renewables",
    "ux",
    "ux prototyping",
    "ux-prototyping",
    "vaccine schedules",
    "vaccine-schedules",
    "validated",
    "valuation",
    "valuation analysis",
    "valuation modeling",
    "valuation-analysis",
    "value-added",
    "variance analysis",
    "variance-analysis",
    "vc-pe",
    "vcpe",
    "veeva",
    "vehicle maintenance",
    "vehicle-maintenance",
    "vendor coordination",
    "vendor management",
    "vendor mgmt",
    "vendor performance",
    "vendor scorecards",
    "vendor sourcing",
    "vendor-coordination",
    "vendor-management",
    "vendor-scorecards",
    "vendor-sourcing",
    "venture capital / private equity",
    "venue logistics",
    "venue-logistics",
    "verbal communication",
    "version control",
    "vet",
    "veterinary",
    "veterinary advisor",
    "veterinary analyst",
    "veterinary analytics",
    "veterinary compliance",
    "veterinary consultant",
    "veterinary coordinator",
    "veterinary manager",
    "veterinary operations",
    "veterinary optimization",
    "veterinary reporting",
    "veterinary specialist",
    "veterinary strategy",
    "veterinary technician",
    "video production",
    "video production analyst",
    "video production compliance",
    "video production consultant",
    "video production coordinator",
    "video production director",
    "video production manager",
    "video production operations",
    "video production optimization",
    "video production reporting",
    "video production specialist",
    "video production strategist",
    "video production strategy",
    "video-production",
    "virtual reality",
    "vision screening",
    "vision-screening",
    "visual design",
    "visual interface",
    "visual-design",
    "voice of customer",
    "voice-of-customer",
    "volunteer coordination",
    "volunteer-coordination",
    "vr",
    "vulnerability management",
    "vulnerability mgmt",
    "vulnerability-management",
    "wallet integration",
    "wallet operations",
    "wallet ops",
    "wallet-integration",
    "wallet-operations",
    "warehouse integration",
    "warehouse operations",
    "warehouse ops",
    "warehouse-integration",
    "warehouse-operations",
    "wealth",
    "wealth management",
    "wealth management / financial planning",
    "wealth management advisor",
    "wealth management analyst",
    "wealth management associate",
    "wealth management compliance",
    "wealth management consultant",
    "wealth management manager",
    "wealth management operations",
    "wealth management operations manager",
    "wealth management optimization",
    "wealth management reporting",
    "wealth management specialist",
    "wealth management strategy",
    "wealth mgmt",
    "wealth preservation",
    "wealth strategy",
    "wealth-management",
    "wealth-preservation",
    "web3",
    "web3 / crypto / blockchain",
    "web3-crypto",
    "weights & biases",
    "wellness",
    "wellness advisor",
    "wellness analyst",
    "wellness analytics",
    "wellness business partner",
    "wellness compliance",
    "wellness consultant",
    "wellness coordinator",
    "wellness manager",
    "wellness operations",
    "wellness optimization",
    "wellness plans",
    "wellness reporting",
    "wellness specialist",
    "wellness strategy",
    "wellness-plans",
    "westlaw",
    "wind operations",
    "wind ops",
    "wind-operations",
    "wireshark",
    "wms",
    "won",
    "word",
    "workday",
    "workflow coordination",
    "workflow execution",
    "workflow management",
    "workflow monitoring",
    "workflow optimization",
    "workforce planning",
    "workforce-planning",
    "workpapers",
    "workshops",
    "written communication",
    "wrote",
    "xind",
    "yardi",
    "yield forecasting",
    "yield optimization",
    "yield-forecasting",
    "yield-optimization",
    "zendesk"
] as const;