/**
 * Recon: resolve candidate company career pages to a concrete ATS board.
 *
 * Uses the SAME discovery code the production sync uses (`discoverJobSource`), so anything
 * that resolves here will resolve in `api/jobs-sync.ts` too. Discovery is deliberately the
 * cheap half of the pipeline: it fingerprints `{domain}/careers` and probes lightweight
 * board endpoints, so probing 100 companies does not download 100 full job boards.
 *
 * Usage: npx esbuild ... && node dist/... (see scripts/fetch-career-jobs.ts for the runner)
 */

import {
  discoverJobSource,
  fetchSourceJobs,
  type JobProvider,
  type JobSourceCompany,
  type ResolvedJobSource,
} from '../api/_lib/jobs';

/**
 * Candidate employers: legitimate, mid-size companies (mostly B2B / vertical SaaS / dev
 * tooling / fintech infra) that an ordinary jobseeker would not have heard of — the point
 * being to surface postings the big-name aggregators bury.
 *
 * No provider/slug is declared on purpose: discovery fingerprints the careers page first and
 * falls back to probing domain-derived + name-derived tokens, which is what we want to
 * verify for newly added companies.
 */
export const CANDIDATE_COMPANIES: JobSourceCompany[] = [
  // ---- wave 1 ----
  // ---- dev tooling / infrastructure ----
  { name: 'Mercury', domain: 'mercury.com' },
  { name: 'Retool', domain: 'retool.com' },
  { name: 'Temporal', domain: 'temporal.io' },
  { name: 'Postman', domain: 'postman.com' },
  { name: 'Fastly', domain: 'fastly.com' },
  { name: 'DigitalOcean', domain: 'digitalocean.com' },
  { name: 'HashiCorp', domain: 'hashicorp.com' },
  { name: 'LaunchDarkly', domain: 'launchdarkly.com' },
  { name: 'Mux', domain: 'mux.com' },
  { name: 'PlanetScale', domain: 'planetscale.com' },
  { name: 'Cockroach Labs', domain: 'cockroachlabs.com' },
  { name: 'Timescale', domain: 'timescale.com' },
  { name: 'Turso', domain: 'turso.tech' },
  { name: 'Fly.io', domain: 'fly.io' },
  { name: 'Railway', domain: 'railway.app' },
  { name: 'Sentry', domain: 'sentry.io' },
  { name: 'Honeycomb', domain: 'honeycomb.io' },
  { name: 'Grafana Labs', domain: 'grafana.com' },
  { name: 'InfluxData', domain: 'influxdata.com' },
  { name: 'Snyk', domain: 'snyk.io' },
  { name: 'Semgrep', domain: 'semgrep.dev' },
  { name: 'Sourcegraph', domain: 'sourcegraph.com' },
  { name: 'Elastic', domain: 'elastic.co' },
  { name: 'Chronosphere', domain: 'chronosphere.io' },
  // ---- AI / data infrastructure (non-household names) ----
  { name: 'Together AI', domain: 'together.ai' },
  { name: 'Baseten', domain: 'baseten.co' },
  { name: 'Replicate', domain: 'replicate.com' },
  { name: 'Weights & Biases', domain: 'wandb.com' },
  { name: 'Qdrant', domain: 'qdrant.tech' },
  { name: 'Chroma', domain: 'trychroma.com' },
  { name: 'Pinecone', domain: 'pinecone.io' },
  { name: 'Cohere', domain: 'cohere.com' },
  { name: 'Mistral AI', domain: 'mistral.ai' },
  { name: 'Hugging Face', domain: 'huggingface.co' },
  { name: 'Glean', domain: 'glean.com' },
  { name: 'Abridge', domain: 'abridge.com' },
  { name: 'Sardine', domain: 'sardine.ai' },
  { name: 'Nominal', domain: 'nominal.io' },
  // ---- data / analytics ----
  { name: 'Fivetran', domain: 'fivetran.com' },
  { name: 'dbt Labs', domain: 'getdbt.com' },
  { name: 'Hex', domain: 'hex.tech' },
  { name: 'Mixpanel', domain: 'mixpanel.com' },
  { name: 'Amplitude', domain: 'amplitude.com' },
  { name: 'Airtable', domain: 'airtable.com' },
  { name: 'Sigma Computing', domain: 'sigmacomputing.com' },
  { name: 'Monte Carlo', domain: 'montecarlodata.com' },
  { name: 'Atlan', domain: 'atlan.com' },
  { name: 'Census', domain: 'getcensus.com' },
  { name: 'Hightouch', domain: 'hightouch.com' },
  // ---- fintech / payments infrastructure ----
  { name: 'Modern Treasury', domain: 'moderntreasury.com' },
  { name: 'Melio', domain: 'melio.com' },
  { name: 'Alloy', domain: 'alloy.com' },
  { name: 'Unit', domain: 'unit.co' },
  { name: 'Increase', domain: 'increase.com' },
  { name: 'Lithic', domain: 'lithic.com' },
  { name: 'Highnote', domain: 'highnote.com' },
  { name: 'Moov', domain: 'moov.io' },
  { name: 'Column', domain: 'column.com' },
  { name: 'Marqeta', domain: 'marqeta.com' },
  { name: 'Betterment', domain: 'betterment.com' },
  { name: 'Wealthfront', domain: 'wealthfront.com' },
  { name: 'Acorns', domain: 'acorns.com' },
  { name: 'Public', domain: 'public.com' },
  { name: 'Alpaca', domain: 'alpaca.markets' },
  { name: 'DriveWealth', domain: 'drivewealth.com' },
  { name: 'Dave', domain: 'dave.com' },
  { name: 'Brigit', domain: 'brigit.com' },
  { name: 'Pindrop', domain: 'pindrop.com' },
  { name: 'Everlaw', domain: 'everlaw.com' },
  { name: 'Ironclad', domain: 'ironcladapp.com' },
  // ---- vertical SaaS / operations ----
  { name: 'Brightwheel', domain: 'mybrightwheel.com' },
  { name: 'Clipboard Health', domain: 'clipboardhealth.com' },
  { name: 'Cresta', domain: 'cresta.com' },
  { name: 'Clay', domain: 'clay.com' },
  { name: 'Project44', domain: 'project44.com' },
  { name: 'ShipBob', domain: 'shipbob.com' },
  { name: 'Gorgias', domain: 'gorgias.com' },
  { name: 'Attentive', domain: 'attentive.com' },
  { name: 'Postscript', domain: 'postscript.io' },
  { name: 'Yotpo', domain: 'yotpo.com' },
  { name: 'Klaviyo', domain: 'klaviyo.com' },
  { name: 'Benchling', domain: 'benchling.com' },
  { name: 'Lattice', domain: 'lattice.com' },
  { name: 'Deel', domain: 'deel.com' },
  { name: 'Remote', domain: 'remote.com' },
  { name: 'HiBob', domain: 'hibob.com' },
  { name: 'Personio', domain: 'personio.com' },
  { name: 'Leapsome', domain: 'leapsome.com' },

  // ---- wave 2: deliberately *not* household names ----
  //
  // Same thesis as above, pushed much wider: vertical SaaS, developer tooling, data /
  // observability, security, fintech infrastructure and applied AI whose postings an
  // aggregator buries under the big brands. No provider/slug is declared, so recon proves
  // each board is real before it is added to the production seed.

  // developer tooling / cloud infrastructure
  { name: 'Render', domain: 'render.com' },
  { name: 'Neon', domain: 'neon.tech' },
  { name: 'Prisma', domain: 'prisma.io' },
  { name: 'Hasura', domain: 'hasura.io' },
  { name: 'Apollo GraphQL', domain: 'apollographql.com' },
  { name: 'Redpanda', domain: 'redpanda.com' },
  { name: 'Materialize', domain: 'materialize.com' },
  { name: 'ClickHouse', domain: 'clickhouse.com' },
  { name: 'Starburst', domain: 'starburst.io' },
  { name: 'Confluent', domain: 'confluent.io' },
  { name: 'Prefect', domain: 'prefect.io' },
  { name: 'Dagster Labs', domain: 'dagster.io' },
  { name: 'Airbyte', domain: 'airbyte.com' },
  { name: 'Estuary', domain: 'estuary.dev' },
  { name: 'Netlify', domain: 'netlify.com' },
  { name: 'Pulumi', domain: 'pulumi.com' },
  { name: 'Spacelift', domain: 'spacelift.io' },
  { name: 'env0', domain: 'env0.com' },
  { name: 'incident.io', domain: 'incident.io' },
  { name: 'Rootly', domain: 'rootly.com' },
  { name: 'FireHydrant', domain: 'firehydrant.com' },
  { name: 'Komodor', domain: 'komodor.com' },
  { name: 'Vantage', domain: 'vantage.sh' },
  { name: 'CloudZero', domain: 'cloudzero.com' },
  { name: 'Cast AI', domain: 'cast.ai' },
  { name: 'Koyeb', domain: 'koyeb.com' },
  { name: 'Northflank', domain: 'northflank.com' },
  { name: 'Sanity', domain: 'sanity.io' },
  { name: 'Contentful', domain: 'contentful.com' },
  { name: 'Storyblok', domain: 'storyblok.com' },
  { name: 'Builder.io', domain: 'builder.io' },
  { name: 'Strapi', domain: 'strapi.io' },
  { name: 'Directus', domain: 'directus.io' },
  { name: 'Teleport', domain: 'goteleport.com' },
  { name: 'Tailscale', domain: 'tailscale.com' },
  { name: 'Chainguard', domain: 'chainguard.dev' },
  { name: 'Socket', domain: 'socket.dev' },
  { name: 'Endor Labs', domain: 'endorlabs.com' },
  { name: 'Cycode', domain: 'cycode.com' },
  { name: 'Jit', domain: 'jit.io' },
  { name: 'Aikido Security', domain: 'aikido.dev' },

  // observability / logs / APM
  { name: 'Sumo Logic', domain: 'sumologic.com' },
  { name: 'Mezmo', domain: 'mezmo.com' },
  { name: 'Coralogix', domain: 'coralogix.com' },
  { name: 'Axiom', domain: 'axiom.co' },
  { name: 'PagerDuty', domain: 'pagerduty.com' },
  { name: 'Arize AI', domain: 'arize.com' },
  { name: 'Fiddler AI', domain: 'fiddler.ai' },
  { name: 'Galileo', domain: 'galileo.ai' },
  { name: 'Braintrust', domain: 'braintrust.dev' },
  { name: 'Humanloop', domain: 'humanloop.com' },
  { name: 'Vellum', domain: 'vellum.ai' },

  // AI / ML infrastructure and apps
  { name: 'LangChain', domain: 'langchain.com' },
  { name: 'LlamaIndex', domain: 'llamaindex.ai' },
  { name: 'Unstructured', domain: 'unstructured.io' },
  { name: 'Deepgram', domain: 'deepgram.com' },
  { name: 'AssemblyAI', domain: 'assemblyai.com' },
  { name: 'Speechmatics', domain: 'speechmatics.com' },
  { name: 'Gladia', domain: 'gladia.io' },
  { name: 'Runway', domain: 'runwayml.com' },
  { name: 'Synthesia', domain: 'synthesia.io' },
  { name: 'HeyGen', domain: 'heygen.com' },
  { name: 'Descript', domain: 'descript.com' },
  { name: 'ElevenLabs', domain: 'elevenlabs.io' },
  { name: 'Perplexity', domain: 'perplexity.ai' },
  { name: 'Sierra', domain: 'sierra.ai' },
  { name: 'Decagon', domain: 'decagon.ai' },
  { name: 'Parloa', domain: 'parloa.com' },
  { name: 'Labelbox', domain: 'labelbox.com' },
  { name: 'Snorkel AI', domain: 'snorkel.ai' },

  // data / analytics
  { name: 'Segment', domain: 'segment.com' },
  { name: 'RudderStack', domain: 'rudderstack.com' },
  { name: 'mParticle', domain: 'mparticle.com' },
  { name: 'Heap', domain: 'heap.io' },
  { name: 'PostHog', domain: 'posthog.com' },
  { name: 'Mode', domain: 'mode.com' },
  { name: 'Omni', domain: 'omni.co' },
  { name: 'Preset', domain: 'preset.io' },
  { name: 'Snowplow', domain: 'snowplow.io' },
  { name: 'Dremio', domain: 'dremio.com' },
  { name: 'Firebolt', domain: 'firebolt.io' },

  // security
  { name: 'Wiz', domain: 'wiz.io' },
  { name: 'Orca Security', domain: 'orca.security' },
  { name: 'Sysdig', domain: 'sysdig.com' },
  { name: 'Aqua Security', domain: 'aquasec.com' },
  { name: 'Abnormal Security', domain: 'abnormal.ai' },
  { name: 'Armis', domain: 'armis.com' },
  { name: 'Axonius', domain: 'axonius.com' },
  { name: 'JupiterOne', domain: 'jupiterone.com' },
  { name: 'Vanta', domain: 'vanta.com' },
  { name: 'Drata', domain: 'drata.com' },
  { name: 'Secureframe', domain: 'secureframe.com' },
  { name: 'Thoropass', domain: 'thoropass.com' },
  { name: 'Transcend', domain: 'transcend.io' },
  { name: 'Osano', domain: 'osano.com' },
  { name: 'BigID', domain: 'bigid.com' },
  { name: 'Cyberhaven', domain: 'cyberhaven.com' },
  { name: 'Netskope', domain: 'netskope.com' },
  { name: 'Cato Networks', domain: 'catonetworks.com' },

  // fintech / payments infrastructure
  { name: 'Teller', domain: 'teller.io' },
  { name: 'Dwolla', domain: 'dwolla.com' },
  { name: 'Method Financial', domain: 'methodfi.com' },
  { name: 'Astra', domain: 'astra.finance' },
  { name: 'Argyle', domain: 'argyle.com' },
  { name: 'Pinwheel', domain: 'pinwheelapi.com' },
  { name: 'Middesk', domain: 'middesk.com' },
  { name: 'Persona', domain: 'withpersona.com' },
  { name: 'Unit21', domain: 'unit21.ai' },
  { name: 'Hawk AI', domain: 'hawk.ai' },
  { name: 'Finix', domain: 'finix.com' },
  { name: 'Payrix', domain: 'payrix.com' },
  { name: 'Check', domain: 'checkhq.com' },
  { name: 'Rainforest', domain: 'rainforestpay.com' },

  // vertical SaaS / operations / commerce
  { name: 'ServiceTitan', domain: 'servicetitan.com' },
  { name: 'Procore', domain: 'procore.com' },
  { name: 'Housecall Pro', domain: 'housecallpro.com' },
  { name: 'Jobber', domain: 'getjobber.com' },
  { name: 'BuildOps', domain: 'buildops.com' },
  { name: 'Motive', domain: 'gomotive.com' },
  { name: 'FourKites', domain: 'fourkites.com' },
  { name: 'Narvar', domain: 'narvar.com' },
  { name: 'Loop Returns', domain: 'loopreturns.com' },
  { name: 'Gladly', domain: 'gladly.com' },
  { name: 'Kustomer', domain: 'kustomer.com' },
  { name: 'Front', domain: 'front.com' },
  { name: 'Help Scout', domain: 'helpscout.com' },
  { name: 'Podium', domain: 'podium.com' },
  { name: 'Sprout Social', domain: 'sproutsocial.com' },
  { name: 'Buffer', domain: 'buffer.com' },
  { name: 'Hootsuite', domain: 'hootsuite.com' },
  { name: 'BigCommerce', domain: 'bigcommerce.com' },
  { name: 'Bolt', domain: 'bolt.com' },
  { name: 'Recharge', domain: 'rechargepayments.com' },
  { name: 'Ordergroove', domain: 'ordergroove.com' },
  { name: 'Rokt', domain: 'rokt.com' },
  { name: 'Constructor', domain: 'constructor.io' },
  { name: 'Algolia', domain: 'algolia.com' },
  { name: 'Bloomreach', domain: 'bloomreach.com' },
  { name: 'Nosto', domain: 'nosto.com' },
  { name: 'Searchspring', domain: 'searchspring.com' },

  // HR / people / productivity / design
  { name: 'Rippling', domain: 'rippling.com' },
  { name: 'Velocity Global', domain: 'velocityglobal.com' },
  { name: 'Papaya Global', domain: 'papayaglobal.com' },
  { name: 'Multiplier', domain: 'multiplier.com' },
  { name: 'Oyster', domain: 'oysterhr.com' },
  { name: '15Five', domain: '15five.com' },
  { name: 'Culture Amp', domain: 'cultureamp.com' },
  { name: 'Bonusly', domain: 'bonusly.com' },
  { name: 'Kazoo', domain: 'kazoo.com' },
  { name: 'Achievers', domain: 'achievers.com' },
  { name: 'Webflow', domain: 'webflow.com' },
  { name: 'Framer', domain: 'framer.com' },
  { name: 'Miro', domain: 'miro.com' },
  { name: 'Mural', domain: 'mural.co' },
  { name: 'Lucid', domain: 'lucid.co' },
  { name: 'Whimsical', domain: 'whimsical.com' },
  { name: 'Zeplin', domain: 'zeplin.io' },
  { name: 'Loom', domain: 'loom.com' },
  { name: 'Grain', domain: 'grain.com' },
  { name: 'Gong', domain: 'gong.io' },
  { name: 'Clari', domain: 'clari.com' },
  { name: 'Outreach', domain: 'outreach.io' },
  { name: 'Salesloft', domain: 'salesloft.com' },
  { name: 'Apollo.io', domain: 'apollo.io' },
  { name: 'Lusha', domain: 'lusha.com' },
  { name: 'Intercom', domain: 'intercom.com' },

  // health / fintech / applied AI (mid-size)
  { name: 'Oscar Health', domain: 'hioscar.com' },
  { name: 'Carbon Health', domain: 'carbonhealth.com' },
  { name: 'Cedar', domain: 'cedar.com' },
  { name: 'Notable', domain: 'notablehealth.com' },
  { name: 'Tempus', domain: 'tempus.com' },
  { name: 'Datavant', domain: 'datavant.com' },
  { name: 'Health Gorilla', domain: 'healthgorilla.com' },
  { name: 'Redox', domain: 'redoxengine.com' },
  { name: 'Zocdoc', domain: 'zocdoc.com' },
  { name: 'Headway', domain: 'headway.co' },
  { name: 'Alma', domain: 'helloalma.com' },
  { name: 'Grow Therapy', domain: 'growtherapy.com' },
  { name: 'Spring Health', domain: 'springhealth.com' },
  { name: 'Lyra Health', domain: 'lyrahealth.com' },
  { name: 'Modern Health', domain: 'modernhealth.com' },
  { name: 'Talkspace', domain: 'talkspace.com' },
  { name: 'Doximity', domain: 'doximity.com' },
  { name: 'Flatiron Health', domain: 'flatiron.com' },
  { name: 'Komodo Health', domain: 'komodohealth.com' },
];

/** Full-payload fetch for one already-resolved board (used after discovery confirms it). */
export async function fetchResolved(source: ResolvedJobSource) {
  return fetchSourceJobs(source);
}

export { discoverJobSource, fetchSourceJobs };
export type { JobProvider, ResolvedJobSource };
